#! /bin/sh
#
# Initscript for k-shaper 
#
# Copyright 2005, Massimiliano Leone <massimiliano.leone@studio.unibo.it>, GPL licens, GPL license
#
# Version:	0.3
#

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="k-shaper"
NAME=k-shaper
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#
#	Function that starts the daemon/service.
#
d_start() {
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -a
}

#
#	Function that stops the daemon/service.
#
d_stop() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --name $NAME -f
}


case "$1" in
  start)
	echo -n "Starting $NAME..."
	d_start
	echo "."
	;;
  stop)
	echo -n "Stopping $NAME..."
	d_stop
	echo "."
	;;
  restart)
	echo -n "Restarting $NAME..."
	d_stop
	sleep 1
	d_start
	echo "."
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
